# Generated by Django 3.1.1 on 2020-10-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0002_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminpanel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='newfolder')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='login',
        ),
    ]
