# Generated by Django 3.1.2 on 2020-10-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0004_adminfruits'),
    ]

    operations = [
        migrations.CreateModel(
            name='admingreens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='newfolder')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='admintubers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='newfolder')),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='adminveg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='newfolder')),
                ('desc', models.TextField()),
            ],
        ),
    ]
