# Generated by Django 3.1.2 on 2020-10-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriculture', '0005_admingreens_admintubers_adminveg'),
    ]

    operations = [
        migrations.CreateModel(
            name='soil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soiltype', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='newfolder')),
            ],
        ),
    ]
